[program:datahub-parallel]
command=/bin/bash -c "php -dmemory_limit=-1 /var/www/html/bin/console datahub:data-importer:process-queue-parallel && sleep 60"
numprocs=1
autostart=true
autorestart=true
startretries=10
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/supervisor/datahub-consume.log
stderr_logfile=/var/log/supervisor/datahub-consume.err.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=false

[program:datahub-sequential]
command=/bin/bash -c "php -dmemory_limit=-1 /var/www/html/bin/console datahub:data-importer:process-queue-sequential && sleep 60"
numprocs=1
autostart=true
autorestart=true
startretries=10
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/supervisor/datahub-consume.log
stderr_logfile=/var/log/supervisor/datahub-consume.err.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=false
