pimcore:
    objects:
        custom_layouts:
            definitions:
                ba54fdc4-194b-4336-a30c-f24aa6d57696:
                    id: ba54fdc4-194b-4336-a30c-f24aa6d57696
                    name: stockManager
                    description: ''
                    creationDate: 1760173327
                    modificationDate: 1763280971
                    userOwner: 2
                    classId: product
                    layoutDefinitions:
                        name: pimcore_root
                        type: null
                        region: null
                        title: null
                        width: 0
                        height: 0
                        collapsible: false
                        collapsed: false
                        bodyStyle: null
                        datatype: layout
                        children:
                            -
                                name: Layout
                                type: null
                                region: null
                                title: Availability
                                width: ''
                                height: ''
                                collapsible: false
                                collapsed: false
                                bodyStyle: ''
                                datatype: layout
                                children:
                                    -
                                        name: whAvail
                                        title: 'Warehouse Availability'
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: fieldcollections
                                        relationType: false
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        allowedTypes:
                                            - warehouseAvailability
                                        lazyLoading: true
                                        maxItems: null
                                        disallowAddRemove: false
                                        disallowReorder: false
                                        collapsed: false
                                        collapsible: false
                                        border: false
                                        datatype: data
                                locked: false
                                fieldtype: panel
                                layout: null
                                border: false
                                icon: ''
                                labelWidth: 100
                                labelAlign: left
                        locked: false
                        fieldtype: panel
                        layout: null
                        border: false
                        icon: null
                        labelWidth: 100
                        labelAlign: left
                    default: 0
