pimcore:
    general:
        domain: ''
        redirect_to_maindomain: false
        valid_languages:
            - it
            - en
            - fr
            - de
            - es
            - nl_NL
            - pl
        fallback_languages:
            it: ''
            en: ''
            fr: ''
            de: ''
            es: ''
            nl_NL: ''
            pl: ''
        required_languages:
            - en
        default_language: en
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: ''
            localized:
                it: ''
                en: ''
                fr: ''
                de: ''
                es: ''
                nl_NL: ''
                pl: ''
    objects:
        versions:
            days: null
            steps: null
    assets:
        versions:
            days: null
            steps: null
    email: {  }
