pimcore_data_hub:
    configurations:
        import-brands:
            general:
                active: true
                type: dataImporterDataObject
                name: import-brands
                description: ''
                group: ''
                path: null
                modificationDate: 1760545443
                createDate: 1759954994
            loaderConfig:
                type: push
                settings:
                    apiKey: 8f1e59c97755a296c812e8f8c118bc7a
                    ignoreNotEmptyQueue: 'on'
            interpreterConfig:
                type: json
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: brand
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: name
                        attributeName: brandName
                        language: en
                        includeUnpublished: true
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /brands
                locationUpdateStrategy:
                    type: staticPath
                    settings:
                        path: /brands
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: parallel
                idDataIndex: ''
            mappingConfig:
                -
                    label: key
                    dataSourceIndex:
                        - name
                    settings:
                        mode: both
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                mode: both
                            type: trim
                -
                    label: name
                    dataSourceIndex:
                        - name
                    settings:
                        mode: both
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: brandName
                            language: en
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                mode: both
                            type: trim
            executionConfig:
                scheduleType: recurring
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
